### 注册
POST {{auth_host}}/register
Content-Type: application/json

{
  "password": "1234",
  "confirmpwd": "1234",
  "username": "i1"
}

### 学生授权
POST {{auth_host}}/oauth/token?client_id=WebApp&client_secret=WebApp&grant_type=password&username=
    {"username": "s1", "authType":"password","password": 1234}&scope=all

### 讲师授权
POST {{auth_host}}/oauth/token?client_id=WebApp&client_secret=WebApp&grant_type=password&username=
    {"username": "i1", "authType":"password","password": 1234}&scope=all

### 校验
POST {{auth_host}}/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidGVjaGllLW5lc3QiXSwidXNlcl9uYW1lIjoie1wiY3JlYXRlVGltZVwiOlwiMjAyNC0wNC0wNFQwMDowMDo1Ni42MzBcIixcImlkXCI6XCJkMzgwZWU3OTY0MGE0YzM5XCIsXCJzdGF0dXNcIjpcIjFcIixcInVUeXBlXCI6MixcInVwZGF0ZVRpbWVcIjpcIjIwMjQtMDQtMDNUMTY6MDA6NTYuNjcyXCIsXCJ1c2VybmFtZVwiOlwiaTFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzEyMTY3MzAxLCJhdXRob3JpdGllcyI6WyJST0xFX0lOU1RSVUNUT1IiXSwianRpIjoic0ctamY3c0VPN0ktSFNabl9pcGtOeUN5Z0s4IiwiY2xpZW50X2lkIjoiV2ViQXBwIn0.fwg1ZtxG6MO5uDvDBflzEGt38nh9VyWNoz276Gnx0Tk
