###
POST {{content_host}}/api/content/course/list
Content-Type: application/json

{
  "auditStatus": "202004",
  "publishStatus": "203001",
  "courseName": "java"
}

<> 2024-03-02T101611.200.json

### 课程分类查询
GET {{content_host}}/api/content/course-category/tree-nodes

###  授权
POST http://localhost:5678/api/auth/oauth/token?client_id=WebApp&client_secret=WebApp&grant_type=password&username={"username": "stu1", "authType":"password","password": 111111}&scope=all

### 校验
POST http://localhost:5678/api/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidGVjaGllLW5lc3QiXSwidXNlcl9uYW1lIjoie1wiYmlydGhkYXlcIjpcIjIwMjItMDktMjhUMTk6Mjg6NDZcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MFwiLFwibmFtZVwiOlwi5a2m55SfMVwiLFwibmlja25hbWVcIjpcIuWkp-awtOeJm1wiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdHUxXCIsXCJ1c2VycGljXCI6XCJodHRwOi8vZmlsZS41MXh1ZWNoZW5nLmNuL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzExMTE4NDI0LCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJaMmJLMDlPenFTSFpzNDVGcHRQeFk5MWs5TlEiLCJjbGllbnRfaWQiOiJXZWJBcHAifQ.t7TgQ4gzg_4iiFtYiRdkj6r9olZOsEvdD7VpcyUkfgc

### 使用令牌访问课程资源
GET {{content_host}}/api/content/course/74
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidGVjaGllLW5lc3QiXSwidXNlcl9uYW1lIjoiemhhbmdzYW4iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzExMTE1NjAzLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJrVHFJODkzbDZBZmFKVjBJTHg1S25fVEozMzgiLCJjbGllbnRfaWQiOiJXZWJBcHAifQ.MKl0q4vsPD9yCAaqJC3FsdnrZnGPbPIZ9HK_gAAWRYo


### 网关认证
GET {{gateway_host}}/api/content/course/74
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidGVjaGllLW5lc3QiXSwidXNlcl9uYW1lIjoiemhhbmdzYW4iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzExMTE1NjAzLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJrVHFJODkzbDZBZmFKVjBJTHg1S25fVEozMzgiLCJjbGllbnRfaWQiOiJXZWJBcHAifQ.MKl0q4vsPD9yCAaqJC3FsdnrZnGPbPIZ9HK_gAAWRY

### 检查用户信息
GET {{content_host}}/api/content/course/74
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidGVjaGllLW5lc3QiXSwidXNlcl9uYW1lIjoie1wiYmlydGhkYXlcIjpcIjIwMjItMDktMjhUMTk6Mjg6NDZcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MFwiLFwibmFtZVwiOlwi5a2m55SfMVwiLFwibmlja25hbWVcIjpcIuWkp-awtOeJm1wiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdHUxXCIsXCJ1c2VycGljXCI6XCJodHRwOi8vZmlsZS41MXh1ZWNoZW5nLmNuL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzExMTE5MTc1LCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJLNnJpbXRtT01pMkNJdnRNckFfQlJSN216dWMiLCJjbGllbnRfaWQiOiJXZWJBcHAifQ.T_OTombOud-y41ReF8TzyigS1twnhu2vvsRuzltzfPw
