###
POST {{content_host}}/api/content/course/list
Content-Type: application/json

{
  "auditStatus": "202004",
  "publishStatus": "203001",
  "courseName": "java"
}

<> 2024-03-02T101611.200.json

### 课程分类查询
GET {{content_host}}/api/content/course-category/tree-nodes

###  授权
POST http://localhost:5678/api/auth/oauth/token?client_id=WebApp&client_secret=WebApp&grant_type=password&username={"username": "stu1", "authType":"password","password": 111111}&scope=all

### 校验
POST http://localhost:5678/api/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidGVjaGllLW5lc3QiXSwidXNlcl9uYW1lIjoie1wiYmlydGhkYXlcIjpcIjIwMjItMDktMjhUMTk6Mjg6NDZcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MFwiLFwibmFtZVwiOlwi5a2m55SfMVwiLFwibmlja25hbWVcIjpcIuWkp-awtOeJm1wiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdHUxXCIsXCJ1c2VycGljXCI6XCJodHRwOi8vZmlsZS41MXh1ZWNoZW5nLmNuL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzExMjU0NjIwLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJVTGNrUzF5M19tSUZDVmZld3EyTU04ZGZrVlUiLCJjbGllbnRfaWQiOiJXZWJBcHAifQ.psuuxoLa8dFjjZr7cp-7Jz_6-d11eRXmlZz_kDcRVTE


### 使用令牌访问课程资源
GET {{content_host}}/api/content/course/74
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidGVjaGllLW5lc3QiXSwidXNlcl9uYW1lIjoie1wiYmlydGhkYXlcIjpcIjIwMjItMDktMjhUMTk6Mjg6NDZcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MFwiLFwibmFtZVwiOlwi5a2m55SfMVwiLFwibmlja25hbWVcIjpcIuWkp-awtOeJm1wiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdHUxXCIsXCJ1c2VycGljXCI6XCJodHRwOi8vZmlsZS41MXh1ZWNoZW5nLmNuL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzExMjU0NjIwLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJVTGNrUzF5M19tSUZDVmZld3EyTU04ZGZrVlUiLCJjbGllbnRfaWQiOiJXZWJBcHAifQ.psuuxoLa8dFjjZr7cp-7Jz_6-d11eRXmlZz_kDcRVTE

### 网关认证
GET {{gateway_host}}/api/content/course/74
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidGVjaGllLW5lc3QiXSwidXNlcl9uYW1lIjoie1wiYmlydGhkYXlcIjpcIjIwMjItMDktMjhUMTk6Mjg6NDZcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MFwiLFwibmFtZVwiOlwi5a2m55SfMVwiLFwibmlja25hbWVcIjpcIuWkp-awtOeJm1wiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdHUxXCIsXCJ1c2VycGljXCI6XCJodHRwOi8vZmlsZS41MXh1ZWNoZW5nLmNuL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzExMjU0NjIwLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJVTGNrUzF5M19tSUZDVmZld3EyTU04ZGZrVlUiLCJjbGllbnRfaWQiOiJXZWJBcHAifQ.psuuxoLa8dFjjZr7cp-7Jz_6-d11eRXmlZz_kDcRVTE

### 检查用户信息
GET {{content_host}}/api/content/course/74
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidGVjaGllLW5lc3QiXSwidXNlcl9uYW1lIjoie1wiYmlydGhkYXlcIjpcIjIwMjItMDktMjhUMTk6Mjg6NDZcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MFwiLFwibmFtZVwiOlwi5a2m55SfMVwiLFwibmlja25hbWVcIjpcIuWkp-awtOeJm1wiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdHUxXCIsXCJ1c2VycGljXCI6XCJodHRwOi8vZmlsZS41MXh1ZWNoZW5nLmNuL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzExMjA1MjEwLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJ4RElGVWRQUWVIYng3LTVnMVhPTy0wREl5ZzgiLCJjbGllbnRfaWQiOiJXZWJBcHAifQ.k8R4i5EzIwkXzTVcx4xQYxmoBV0zYO_e26frKxgy4qE

### 学习
POST {{learning_host}}/api/learning/choosecourse/50



### 申请验证码
POST {{checkcode_host}}/api/checkcode/pic

### 校验验证码
POST {{checkcode_host}}/api/checkcode/verify?key=checkcode:e92546572f6d45f39ceec4748608c2e0&code=KU6U



### 查询课程发布信息
GET {{content_host}}/api/content/r/coursepublish/74

### 查询订单
GET {{order_host}}/api/orders/payresult?payNo=1771937031190089728
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidGVjaGllLW5lc3QiXSwidXNlcl9uYW1lIjoie1wiYmlydGhkYXlcIjpcIjIwMjItMDktMjhUMTk6Mjg6NDZcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MFwiLFwibmFtZVwiOlwi5a2m55SfMVwiLFwibmlja25hbWVcIjpcIuWkp-awtOeJm1wiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdHUxXCIsXCJ1c2VycGljXCI6XCJodHRwOi8vZmlsZS41MXh1ZWNoZW5nLmNuL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzExMzAyNjEzLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJzMHp0TkNIbEhMdURaU3BLOVlpSWVzMzNROW8iLCJjbGllbnRfaWQiOiJXZWJBcHAifQ.ZJ2kuEfRB9ax7h4HlKDvda5ZNa87zxghIg25WbLE4Hs

### 2134
POST http://dango1123.nat300.top/api/orders/receivenotify